### PR TITLE
Added the possibility for the HttpContext to be provided with post data, so that in addition to working with 'GET' it now also supports 'POST'.

### PR DESCRIPTION
**Pull request by kristianhald**
Hi Vadym,

Thanks for library for faking the HttpContext. 

I have used it in my current project and it worked well for the GET methods, however I also needed to do a POST in my tests to ensure that those operations worked.

I did not know if there was another way of doing it, but I made a minor change to your code and would like to hear if you agree on the design choice and if you would mind including the change into your repository and create a new NuGet package.

The overall design change I made was making the FakeWorkerRequest class and the Verb property abstract.
My thinking was, that each instance of FakeHttpContext is directly tied to a specific URL and therefore when creating the FakeHttpContext (Or it could be afterwards as a method, I chose constructor), then it should be possible to select the type of request being made.

If you think another change would be better to achieve the ability to do a post, then please any input is welcome.

With Best Regards
Kristian

### CODE REVIEW

**Comment by vadimzozulya** [comment]
Hi Kristian,

Thanks for PR !

May I suggest another solution: please see [commit](https://github.com/vadimzozulya/FakeHttpContext/commit/8ec0d8c62b5b7efcad835a9ff2ede12f0666aecc)?

It's a bit simpler from my point of view as doesn't require changes in class hierarchy. 

What do you think ?

**Comment by kristianhald** [comment]
Hi Vadym,

Also looks good. Was uncertain if the constructor direction or method direction would be the best way to go.

I have tested the changeset with the tests I have implemented and they all pass nicely. I have but two issues, both minor, in regards to the changeset:
* In the test 'Should_encode_post_data_with_provided_encoding' in the 'FakeHttpContextTests' class, it uses the same hardcoded encoding to verify that the input stream contains the correct data, as provided to the post request. I would expect the HttpContext.Current.Request.ContentEncoding to match the encoding in the InputStream. I believe my implementation had the same problem.
I cannot see an easy way for correcting this.

* The build.ps1 script has a hardcoded path. I would like the $PSScriptRoot change I made to it, to be included as it should allow for other developers to use their own pathing, when pulling the code.

Else everything looks good :)

**Comment by vadimzozulya** [comment]
Hi Kristian,

Maybe constructor is more straight forward, but method looks more human-language-friendly, and for tests I believe it is more important, so i'd stick to the method approach if you don't mind. 

For the first point - I'll try to set `HttpContext.Current.Request.ContentEncoding` to desired one. Does it make sense ?
The second point is 100% valid, it's  my bad, thanks for highlighting!  :)

If you don't mind, I'd add 'simplified version' on top of your changes in this PR just to not loose all fixes that you've done.

**Comment by kristianhald** [comment]
I agree with the method implementation and reading the code, after having seen the implementation.

First point makes good sense. I believe it should match the input stream as that is the only way to provide the information about the encoding.

In regards to adding the simplified version on top, thank you very much.

I look forward to trying a new version of the implementation in a NuGet package. Would you mind writing, when a new package has been created, because then I will remove the one I created from my project and add yours again. :)

**Comment by vadimzozulya** [comment]
Sure, I'll write when the package is pushed.

I just realized, that I created `Request` property in `FakeHttpContext` to be able set some `Http.Context.Request` settings like `Headers` (I need to look to this repo more often :smile:). So. to have all request configuration in one place, my final suggestion is: 
```csharp
...
  using (var context = new FakeHttpContext
  {
     Request = { PostData = new FakePostData(postData, System.Text.Encoding.UTF32) }
  })
...
```
full version is [here](https://github.com/vadimzozulya/FakeHttpContext/commit/69c9a46f4b40defe908dbda5f017d88e3e2343ac).

Do you agree ?

I promise that it's the final suggestion :laughing:

**Comment by kristianhald** [comment]
I think it looks good 👍 
Changes can always be made better :smile:

**Comment by vadimzozulya** [comment]
Hi Kristian, 

The package is pushed : [0.4.0](https://www.nuget.org/packages/FakeHttpContext/0.4.0)

Sorry that it took so long. And again thanks for contribution ! :)

**Comment by kristianhald** [comment]
Hi Vadym,
Thank you very much for adding the change to your library.
I have upgraded my test project and it works well with the change you have made.

**Pull request merged**
