### PR TITLE
Change visibility of FakeHttpContext properties

### PR DESCRIPTION
**Pull request by pixellos**
Its very hard now to create derived implementation that would make use of original FakeHttpContext, can we expose those properties?

### CODE REVIEW

**Comment by vadimzozulya** [comment]
@pixellos, Thanks for your contribution. I'm ok with the change. However could you please share the use case for the inheritance? Maybe just an extensibility point is required, or some features are missed? :)

**Comment by pixellos** [comment]
Yes, In general I need to create custom response with stringWriter  to unit test RazorGenerator generated assemblies.

**Comment by vadimzozulya** [comment]
Could you post a test code sample?  `document.write` - is it JS client size code? Sorry just can't understand how it related to the HttpContext.Response.  BTW `FakeWorkerRequest`, and `FakeHostEnvironment` are internal, so the code in the commit is not compilable...

**Comment by vadimzozulya** [comment]
Please, provide more details and compilable changes :)

**Pull request closed without merging**
